### ISSUE TITLE
Missing library storj-java

### ISSUE THREAD

**Issue by amrouchk** [Storj/java-libstorj#25]
I tried to execute the sample test of java storj in Eclipse IDE on windows and  I got an error says a  library is missed  called storj-java in the File Storj.java 
I already add the jar file and there is no error but when I tried to execute the example it shows this error:
-------------------------------------------------------------------------

Exception in thread "main" java.lang.UnsatisfiedLinkError: no storj-java in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at io.storj.libstorj.Storj.loadLibrary(Storj.java:425)
	at io.storj.libstorj.Storj.<clinit>(Storj.java:409)
	at storjConnection.ConnectionTest.main(ConnectionTest.java:32)
![capture](https://user-images.githubusercontent.com/8835624/47063211-d3397a00-d20c-11e8-8ec5-715acaf68d9b.PNG)
![capture2](https://user-images.githubusercontent.com/8835624/47063313-23b0d780-d20d-11e8-8859-f0ba4c7411c0.PNG)
---------------------------------------

**Comment by RichardLitt** [comment]
Thanks for logging, @amrouchk. Currently, this repository is not being actively maintained, as we're ramping up work on the v3 version of the architecture. Check out [storj/storj](https://github.com/storj/storj) for more on how that is going. 

I am going to close this as unactionable. Again, thank you.

**Comment by amrouchk** [comment]
Thanks for the reply. 
@RichardLitt  I already have a v2 account in Storj and can use it though but how can I use this library as an API to access to storj network. 
is the problem related to the migration to v3 or just misconfiguration in my side?
I hope you can explain to me more about the issue. 
Regards.
