### ISSUE TITLE
After compilation: couldn't find "libstorj-java.so"

### ISSUE THREAD

**Issue by michaldev** [Storj/java-libstorj#3]
Backtrace from Android Studio:
`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.github.michaldev.cryptocloud-RZg4obNaMI23QyX0llxQjg==/base.apk"],nativeLibraryDirectories=[/data/app/com.github.michaldev.cryptocloud-RZg4obNaMI23QyX0llxQjg==/lib/arm64, /system/lib64, /system/vendor/lib64]]] couldn't find "libstorj-java.so"`

In gradle console always is ok.

**Comment by kaloyan-raev** [comment]
If you are building an Android app, I recommend using the https://github.com/Storj/android-libstorj binding, which is based on this one.

If you are building a generic Java app then you can find the libstorj-java.so at `build/libs/jni/shared`. You need to configure your app to load this library, e.g. `-Djava.library.path=build/libs/jni/shared`

**Comment by michaldev** [comment]
Thank You :)
