### ISSUE TITLE
jniSharedLibrary task failed

### ISSUE THREAD

**Issue by jkawamoto** [Storj/java-libstorj#4]
When I tried to compile java-libstorj with libstorj v2.0.0-beta2, I got the following errors.

```
$ cat /home/travis/build/jkawamoto/java-libstorj/build/tmp/compileJniSharedLibraryJniCpp/output.txt
See file:///home/travis/build/jkawamoto/java-libstorj/build/tmp/compileJniSharedLibraryJniCpp/output.txt for all output for compileJniSharedLibraryJniCpp.
compiling storj-java.cpp failed.
/home/travis/build/jkawamoto/java-libstorj/src/main/cpp/storj-java.cpp: In function ‘void Java_io_storj_libstorj_Storj__1downloadFile(JNIEnv*, jobject, jlong, jstring, jstring, jstring, jobject)’:
/home/travis/build/jkawamoto/java-libstorj/src/main/cpp/storj-java.cpp:822:54: error: ‘errno’ was not declared in this scope
         error_callback(env, callbackObject, fileId, -errno, strerror(errno));
                                                      ^
/home/travis/build/jkawamoto/java-libstorj/src/main/cpp/storj-java.cpp: In function ‘void Java_io_storj_libstorj_Storj__1uploadFile(JNIEnv*, jobject, jlong, jstring, jstring, jstring, jobject)���:
/home/travis/build/jkawamoto/java-libstorj/src/main/cpp/storj-java.cpp:985:57: error: ‘errno’ was not declared in this scope
         error_callback(env, callbackObject, localPath, -errno, strerror(errno));
                                                         ^
In file included from /home/travis/build/jkawamoto/java-libstorj/src/main/cpp/storj-java.cpp:19:0:
/home/travis/build/jkawamoto/java-libstorj/libstorj/include/storj.h: At global scope:
/home/travis/build/jkawamoto/java-libstorj/libstorj/include/storj.h:373:20: warning: ‘BUCKET_OP’ defined but not used [-Wunused-variable]
 static const char *BUCKET_OP[] = { "PUSH", "PULL" };
                    ^
Finished compileJniSharedLibraryJniCpp, see full log file:///home/travis/build/jkawamoto/java-libstorj/build/tmp/compileJniSharedLibraryJniCpp/output.txt.
```

The source files are from the master branch at https://github.com/Storj/java-libstorj/commit/72cc87cedbb3143060ed16261a238ee6592aa499.

**Comment by kaloyan-raev** [comment]
This looks strange. [`errno`](http://www.cplusplus.com/reference/cerrno/errno/) should be globally available.

What's your exact OS type and version? And gcc version?

**Comment by jkawamoto** [comment]
* Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
* gcc version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Thanks!

**Comment by kaloyan-raev** [comment]
I launched an old Ubuntu 14.04.1 VM I have, but I don't get this compilation error there.

Perhaps you can try including the `errno.h` header file and see if this helps you, i.e. add the following at the beginning of the `storj-java.cpp` file:

```C
#include <errno.h>
```

**Comment by jkawamoto** [comment]
I included `<cerrno>` since I'm using a C++ compiler and it fixed that error. 

Thank you for your help.

**Comment by kaloyan-raev** [comment]
Great!

Could you push a PR with this change? I'll merge it, if it does not cause regression for other environments.

**Comment by jkawamoto** [comment]
Here you are https://github.com/Storj/java-libstorj/pull/6
